### PR TITLE
Add metrics support

### PR DESCRIPTION
**Pull request by mucsi96**
The `BP_NGINX_STUB_STATUS_PORT` variable exposes a handful of NGINX Server metrics via the [`stub_status`](https://nginx.org/en/docs/http/ngx_http_stub_status_module.html#stub_status) module which provides basic status information on provided port.
This comes handy for monitoring the server. For example using [NGINX Prometheus Exporter](https://github.com/nginxinc/nginx-prometheus-exporter)

### CODE REVIEW

**Comment by ForestEckhardt** [comment]
Hey there, @mucsi96. Would you be willing to look into the unit test failures that we are seeing?

**Comment by mucsi96** [comment]
Thx. I have fixed the build.

**Comment by mucsi96** [comment]
Maybe it would make sense to add an integration test. Let me try to create one.

**Comment by ForestEckhardt** [comment]
> Maybe it would make sense to add an integration test. Let me try to create one.

That would bee appreciated!

**Comment by mucsi96** [comment]
Sure. Integration test added :)

**Review by ForestEckhardt — APPROVED** [review]
This all looks fantastic thanks!

**Pull request merged**
