### PR TITLE
update default version line to 1.20.*

### PR DESCRIPTION
**Pull request by AccraZed**
see #245 :)

### CODE REVIEW

**Comment by arjun024** [comment]
Hi @AccraZed, Thank you for the PR.
Could you please also update the `stable` version from 1.18.x to 1.20.x? See http://web.archive.org/web/20210508151757/http://nginx.org/en/download.html

**Review by arjun024 — CHANGES_REQUESTED** [review]
See comment

**Comment by arjun024** [comment]
@AccraZed As discussed, could you please set the default-version to the mainline version, and also fix the testcase?

**Comment by AccraZed** [comment]
Since 1.19 was found to have a critical vulnerability and default version lines are changing, I'm going to close this PR and open a separate PR with the appropriate changes. I'll also get to branch off main before PRing so make it easier to merge. 

see #258

**Pull request closed without merging**
